ci:
  skip: [pyright]
  autoupdate_schedule: quarterly
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File names
      - id: check-case-conflict
      # File formats
      - id: pretty-format-json
      - id: check-json
      - id: check-toml
      - id: check-yaml
      # Executables
      - id: check-executables-have-shebangs
        exclude: dev-env
      - id: check-shebang-scripts-are-executable
      # Git shenanigans
      - id: check-merge-conflict
      - id: check-added-large-files
      # Python issues
      - id: check-ast
      - id: debug-statements
      # Whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes, --show-fixes]
      - id: ruff-format

  # Remove doc8 while they force old docutils.
  # - repo: https://github.com/PyCQA/doc8
  #   rev: 0.11.2
  #   hooks:
  #     - id: doc8

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.14
    hooks:
      - id: uv-lock

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    # Zizmor version.
    rev: v1.24.1
    hooks:
      # Run the linter.
      - id: zizmor
        args: ["--fix=all"]
