ci:
  skip: [pyright]
  autoupdate_schedule: quarterly
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File names
      - id: check-case-conflict
      # File formats
      - id: pretty-format-json
      - id: check-json
      - id: check-toml
      - id: check-yaml
      # Executables
      - id: check-executables-have-shebangs
        exclude: dev-env
      - id: check-shebang-scripts-are-executable
      # Git shenanigans
      - id: check-merge-conflict
      - id: check-added-large-files
      # Python issues
      - id: check-ast
      - id: debug-statements
      # Whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.409
    hooks:
      - id: pyright
        additional_dependencies:
          - alabaster==1.0.0
          - babel==2.18.0
          - certifi==2026.4.22
          - charset-normalizer==3.4.7
          - colorama==0.4.6 ; sys_platform == 'win32'
          - coverage==7.14.0
          - doc8==0.11.2
          - docutils==0.22.4
          - idna==3.15
          - imagesize==2.0.0
          - iniconfig==2.3.0
          - jinja2==3.1.6
          - markdown-it-py==4.2.0
          - markupsafe==3.0.3
          - mdit-py-plugins==0.6.1
          - mdurl==0.1.2
          - myst-parser==5.1.0
          - nodeenv==1.10.0
          - packaging==26.2
          - pluggy==1.6.0
          - pygments==2.20.0
          - pyright==1.1.409
          - pytest==9.0.3
          - pytest-cov==7.1.0
          - pytest-mock==3.15.1
          - pyyaml==6.0.3
          - requests==2.34.1
          - requests-mock==1.12.1
          - restructuredtext-lint==2.0.2
          - roman-numerals==4.1.0
          - snowballstemmer==3.0.1
          - sphinx==9.0.4 ; python_full_version < '3.12'
          - sphinx==9.1.0 ; python_full_version >= '3.12'
          - sphinx-rtd-theme==3.1.0
          - sphinxcontrib-applehelp==2.0.0
          - sphinxcontrib-devhelp==2.0.0
          - sphinxcontrib-htmlhelp==2.1.0
          - sphinxcontrib-jquery==4.1
          - sphinxcontrib-jsmath==1.0.1
          - sphinxcontrib-qthelp==2.0.0
          - sphinxcontrib-serializinghtml==2.0.0
          - stevedore==5.7.0
          - tomli==2.4.1 ; python_full_version <= '3.11'
          - types-docutils==0.22.3.20260508
          - types-requests==2.33.0.20260513
          - typing-extensions==4.15.0
          - urllib3==2.7.0
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/PyCQA/doc8
    rev: 0.11.2
    hooks:
      - id: doc8

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.14
    hooks:
      - id: uv-lock
