name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: read

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run prek
        uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2.0.3

      - name: Commits back to branch if necessary
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4

  tests:
    strategy:
      matrix:
        python_version: ["3.11", "3.12", "3.13", "3.14"]

    name: "py${{ matrix.python_version }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python_version }}
          enable-cache: false

      - name: Run tests
        run: uv run pytest
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish:
    name: Publish package to PyPI
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - tests
      - lint
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build wheel & sdist
        run: pipx run uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
