name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Pip, Pre-commit & Poetry caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/
          key: ${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dev dependencies
        run: poetry install

      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: success

      - name: Exit if CI did not succeed
        if: steps.wait-for-ci.outputs.conclusion != 'success'
        run: exit 1

      - name: Publish on PyPI
        run: scripts/publish
        env:
          PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"
